# Generated by Django 6.0.3 on 2026-03-19 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_category', models.CharField(choices=[('frozen', 'Frozen'), ('refrigerated', 'Refrigerated'), ('ambient', 'Ambient')], max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('locker_assigned', 'Locker Assigned'), ('ready', 'Ready'), ('picked_up', 'Picked Up'), ('expired', 'Expired'), ('compromised', 'Compromised')], default='submitted', max_length=20)),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_deadline', models.DateTimeField(blank=True, null=True)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'week_number', 'year')},
            },
        ),
    ]
