# Generated by Django 6.0.3 on 2026-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requires_lower_locker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='temperature_category',
            field=models.CharField(blank=True, choices=[('frozen', 'Frozen'), ('refrigerated', 'Refrigerated'), ('ambient', 'Ambient')], max_length=20, null=True),
        ),
    ]
