# Generated by Django 6.0.3 on 2026-04-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='temperature_category',
        ),
    ]
