# Generated by Django 6.0.3 on 2026-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('temperature_category', models.CharField(choices=[('frozen', 'Frozen'), ('refrigerated', 'Refrigerated'), ('ambient', 'Ambient')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='item', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
