# Generated by Django 6.0.3 on 2026-03-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('hygiene', 'Hygiene'), ('other', 'Other')], default='food', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='temperature_category',
            field=models.CharField(choices=[('frozen', 'Frozen'), ('refrigerated', 'Refrigerated'), ('ambient', 'Ambient')], default='ambient', max_length=20),
        ),
    ]
