# Generated by Django 6.0.3 on 2026-04-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='temperature_category',
        ),
    ]
